version: '3.9'

# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development API server with hot reload
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: cidadao-api-dev
    restart: unless-stopped
    environment:
      - APP_ENV=development
      - DEBUG=true
      - DATABASE_URL=postgresql://cidadao:cidadao123@postgres:5432/cidadao_ai
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    ports:
      - "8080:8000"
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./.env:/app/.env:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery worker for development
  celery-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: cidadao-celery-worker
    restart: unless-stopped
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://cidadao:cidadao123@postgres:5432/cidadao_ai
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
    volumes:
      - ./src:/app/src:ro
      - ./.env:/app/.env:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A src.core.celery_app worker --loglevel=info

  # Celery Beat for scheduled tasks
  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: cidadao-celery-beat
    restart: unless-stopped
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://cidadao:cidadao123@postgres:5432/cidadao_ai
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
    volumes:
      - ./src:/app/src:ro
      - ./.env:/app/.env:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A src.core.celery_app beat --loglevel=info

  # Flower for Celery monitoring
  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: cidadao-flower
    restart: unless-stopped
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    command: celery -A src.core.celery_app flower --port=5555

  # Jupyter Lab for development
  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    container_name: cidadao-jupyter
    restart: unless-stopped
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - DATABASE_URL=postgresql://cidadao:cidadao123@postgres:5432/cidadao_ai
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./src:/home/jovyan/src:ro
      - ./data:/home/jovyan/data
    depends_on:
      - postgres
      - redis