# GitHub Pages Configuration
title: "Cidadão.AI - Documentação Técnica"
description: "Sistema Multi-Agente de IA para Transparência Pública Brasileira"
url: "https://anderson-ufrj.github.io"
baseurl: "/cidadao.ai"

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - _site

# Include files
include:
  - _headers
  - .htaccess

# Markdown processor
markdown: kramdown
highlighter: rouge

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site settings
lang: pt-BR
author: Anderson Henrique da Silva
email: andersonhs27@gmail.com

# Social links
github_username: anderson-ufrj
linkedin_username: anderson-henrique-silva

# Analytics (optional)
google_analytics: # Add your GA tracking ID here if needed

# SEO settings
twitter:
  username: # Add if available
  card: summary_large_image

# OpenGraph defaults
og_image: # Add path to a representative image if available

# Collections (if needed in future)
collections_dir: collections

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      
# GitHub Pages specific settings
github: [metadata]